
CREATE DATABASE Project;
GO
USE Project;

DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS KAVIKALS;
DROP TABLE IF EXISTS PRODUCERS;



CREATE TABLE KAVIKALS(KAVI_ID INT PRIMARY KEY,KAVI_NAME VARCHAR(23));
CREATE TABLE PRODUCERS(PRODUCER_ID INT PRIMARY KEY ,PRODUCER_NAME VARCHAR(10));
CREATE TABLE BOOKS(
     BOOK_ID INT PRIMARY KEY,
     TITTLE VARCHAR (10),   
     KAVI_ID INT,
     PRODUCER_ID INT ,
    FOREIGN KEY (KAVI_ID) REFERENCES KAVIKALS(KAVI_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (PRODUCER_ID) REFERENCES PRODUCERS(PRODUCER_ID)
     ON UPDATE CASCADE ON DELETE CASCADE

);


INSERT INTO KAVIKALS (KAVI_ID,KAVI_NAME) VALUES (1,'ASLAM');
INSERT INTO KAVIKALS (KAVI_ID,KAVI_NAME) VALUES (2,'saheer');
INSERT INTO KAVIKALS (KAVI_ID,KAVI_NAME) VALUES (3,'minhaj');

INSERT INTO PRODUCERS (PRODUCER_ID,PRODUCER_NAME)VALUES (1,'RAHMATH');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES (2, 'naseeba');
INSERT INTO PRODUCERS (PRODUCER_ID,PRODUCER_NAME)VALUES (3,'mariya');
INSERT INTO PRODUCERS (PRODUCER_ID,PRODUCER_NAME)VALUES (4,'sadilk');



INSERT INTO BOOKS (BOOK_ID, TITTLE, KAVI_ID, PRODUCER_ID) VALUES
(1, 'BookOne', 1, 1),(2, 'Booktwo', 2, 2),(3, 'Bookthree', 3, 3);


SELECT BOOKS.TITTLE, KAVIKALS.KAVI_NAME
FROM BOOKS
INNER JOIN KAVIKALS ON BOOKS.KAVI_ID=KAVIKALS.KAVI_ID;



    SELECT BOOKS.TITTLE, KAVIKALS.KAVI_NAME
    FROM BOOKS
    LEFT JOIN KAVIKALS ON BOOKS.KAVI_ID = KAVIKALS.KAVI_ID;



SELECT BOOKS.TITTLE, KAVIKALS.KAVI_NAME
FROM BOOKS
RIGHT JOIN KAVIKALS ON BOOKS.KAVI_ID = KAVIKALS.KAVI_ID;



SELECT BOOKS.TITTLE, KAVIKALS.KAVI_NAME
FROM BOOKS
FULL OUTER JOIN KAVIKALS ON BOOKS.KAVI_ID = KAVIKALS.KAVI_ID;



SELECT KAVI_NAME AS NAME FROM KAVIKALS
UNION
SELECT PRODUCER_NAME AS NAME FROM PRODUCERS;


SELECT KAVI_NAME AS NAME FROM KAVIKALS
UNION ALL
SELECT PRODUCER_NAME AS NAME FROM PRODUCERS;




SELECT * FROM KAVIKALS;
SELECT * FROM PRODUCERS;
SELECT * FROM BOOKS;

